### Get service FileTransferService WSDL
GET {{baseURI}}/FileTransferService
Accept: text/xml


### Get service DofusAccountService WSDL
GET {{baseURI}}/DofusAccountService
Accept: text/xml

### Get 100 dofus accounts
POST {{baseURI}}/DofusAccountService HTTP/2
Host: localhost:9091
Content-Type: application/soap+xml
Content-Length: 321

<soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"
                  xmlns:ws="http://webservices.dofusrpa.lkh.coffee/">
   <soapenv:Header/>
   <soapenv:Body>
      <ws:getUntreatedAccounts>
         <limit>10</limit>
      </ws:getUntreatedAccounts>
   </soapenv:Body>
</soapenv:Envelope>

